require('../database/connect')
const express= require("express")
const cors = require("cors")
const app = express()
app.use(cors())
app.use(express.json())
const path = require("path")
const staticDir = path.join(__dirname, "../images")
app.use(express.static(staticDir))
app.use(express.urlencoded({extended:true}))
const userRoutes=require("../routes/user.routes")
app.use("/user",userRoutes)
const eventRoutes=require("../routes/event.routes")
const serviceRoutes=require("../routes/service.routes")
app.use("/event", eventRoutes)
app.use("/service", serviceRoutes)
module.exports = app
